### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by luisfpadovani** [vattercw/IIQ_SBX#1]
Hello, I would like to see with you how you managed to implement unit testing for your development in IIQ.

I am trying to implement Unit Tests for new features that we are creating on a daily basis.

Would it be possible to share some material?

**Comment by shikida** [comment]
Hey, Padovani, nice to see you here, man. I believe you're looking for this https://community.sailpoint.com/t5/IdentityIQ-Forum/Getting-quot-could-not-find-method-quot-Exception-while-running/m-p/164543#M133949 :-D
